from typing import Annotated
from langgraph.graph import MessagesState
import operator

class SQLState(MessagesState):
    question:      str     # user's natural language question
    schema:        str     # DB schema loaded at start
    generated_sql: str     # SQL generated by LLM
    is_write_op:   bool    # True if INSERT/UPDATE/DELETE
    sql_result:    str     # raw result from DB
    explanation:   str     # plain English explanation
    error:         str     # any SQL error message
    retry_count:   int     # how many times we've retried
    approved:      bool    # human approved write operation